### PR TITLE
Add mac arm64 binary

### PR DESCRIPTION
**Pull request by jwokaty**

### CODE REVIEW

**Comment by hpages** [comment]
Hi Jen,

Looks like this PR breaks **biocViews**:
```
hpages@spectre:~$ R CMD INSTALL biocViews
* installing to library ‘/home/hpages/R/R-4.2.r82318/library’
* installing *source* package ‘biocViews’ ...
** using staged installation
** R
Error in parse(outFile) : 
  /home/hpages/github/Bioconductor/biocViews/R/repository.R:17:56: unexpected symbol
16:             type <- "win.binary"
17:         } else if (substr(type, 1, 10) == "mac.binary" or
                                                           ^
ERROR: unable to collate and parse R files for package ‘biocViews’
* removing ‘/home/hpages/R/R-4.2.r82318/library/biocViews’
* restoring previous ‘/home/hpages/R/R-4.2.r82318/library/biocViews’
```
Please make sure to run `R CMD INSTALL`, followed by `R CMD build` and `R CMD check` before committing any change to a package.

Also the use of `stringr::str_replace` introduces an unnecessary dependency on the **stringr** package (note that new deps must be declared in the `Depends` or `Imports` field). Please use `gsub()` instead like you did in `BBS/utils/makePropagationStatusDb.R`. Finally, for a string substitution that doesn't use a regex, it's better (and safer) to use `fixed=TRUE` (this also applies to `BBS/utils/makePropagationStatusDb.R`).
  
Thanks

**Comment by jwokaty** [comment]
Thanks for catching this. I pushed the changes so that I wouldn't run into problems with the builds today, but I think I don't understand what `fixed=TRUE`. I see that in the vignette for `gsub`

```
   fixed: logical.  If ‘TRUE’, ‘pattern’ is a string to be matched as
          is.  Overrides all conflicting arguments.
```

Does this mean it could be a vector if FALSE?

**Comment by hpages** [comment]
The important part of the sentence is "to be matched as is". In other words, when `fixed=TRUE`, `pattern` is not treated as a regex. In your case this means that the dot in `".arm64"` will be match to a dot, which is what you want, rather than to an arbitrary character.

BTW this fix doesn't really need to be mentioned in the NEWS file. NEWS file should focus on summarizing the changes that happened in the package since the last release. This fix just repairs a regression introduced in the previous commit so doesn't count.

Thanks

**Comment by hpages** [comment]
Oh but it looks like in **biocViews** 1.64.5, the dot is gone: `gsub("arm64", "", type) == "mac.binary"`. Is that correct?

**Comment by jwokaty** [comment]
Not correct, I really shouldn't program in the morning on very important things while multitasking other stuff. I downvote myself :-1:

**Pull request merged**
